import type { Metadata } from "next";
import { Nunito_Sans as NunitoSans } from "next/font/google";
import "../globals.css";

export const metadata: Metadata = {
  title: "Devot Tracking Tool",
  description: "Generated by create next app",
};

const nunitoSans = NunitoSans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>{children}</body>
    </html>
  );
}
