import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import "@/themes/devot-theme.css";
import "./globals.css";

import type { Metadata } from "next";
import { Nunito_Sans as NunitoSans } from "next/font/google";
import { PrimeReactProvider } from "primereact/api";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: "Devot Tracking Tool",
  description: "Generated by create next app",
};

const nunitoSans = NunitoSans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider>
        <body className={`${nunitoSans.className} flex flex-column h-screen`}>
          <Header />
          {children}
        </body>
      </PrimeReactProvider>
    </html>
  );
}
